### ISSUE TITLE
why are there two copies of emojiOrdering.txt? 

### ISSUE THREAD

**Issue by srl295** [unicode-org/unicodetools#283]
https://github.com/unicode-org/unicodetools/pull/272 updates `emojiOrdering.txt` in two places.  Why are there two?

One is under the 'dev' files, and the other is in 'src/main/resources' which will be built into the jar.

Who reads these two files? Can we just have one?

@nedley  and @macchiati  ?

**Comment by nedley** [comment]
I could have sworn Markus told us to put regenerated files in dev.

**Comment by nedley** [comment]
Digging deeper, the version in dev is probably superfluous to emoji-ordering-rules.txt in the charts. Still waiting to hear back from @macchiati on that, though.

**Comment by markusicu** [comment]
During development, files that we edit or generate, and publish, should go into a "dev" folder rather than a "15.0.0" folder. Once Unicode 15 is released, the release-equivalent snapshot of each of the "dev" folders will be copied into "15.0.0" folders so that the tools have access to previous versions, while "dev" remains for the development of the next release.

But that's separate from why there is a version of seemingly the same file in both the 13.0.0 / 14.0.0 / dev... folders (relevant to the files under https://github.com/unicode-org/unicodetools/tree/main/unicodetools/data) as well as in a "resources" location (under https://github.com/unicode-org/unicodetools/tree/main/unicodetools/src/main/resources) that will be baked into a .jar file.

Why would the relevant code not read the file from the data folder? It reads other data files (UCD etc.) from the data folder.

**Comment by markusicu** [comment]
PR #276 removed the version in the "dev" folder. As noted above, that seems wrong. @nedley @macchiati

**Comment by nedley** [comment]
The file is not a public one, it is an input to chart production.

**Comment by markusicu** [comment]
> The file is not a public one, it is an input to chart production.

We have most of our data files under https://github.com/unicode-org/unicodetools/tree/main/unicodetools/data including files that contribute to our work but don't get copied to https://www.unicode.org/Public/ including the "source" and "internal" folders under https://github.com/unicode-org/unicodetools/tree/main/unicodetools/data/emoji/dev but also the "data" folder under https://github.com/unicode-org/unicodetools/tree/main/unicodetools/data/security/dev .

Why should this data file be in a different place from most of the other data files?
Does it not make sense to keep historical versions of it like we do for the others?

**Comment by markusicu** [comment]
There are a lot of emoji data files in the place where we now have the only copy of emojiOrdering.txt ([unicodetools/src/main/resources/org/unicode/tools/emoji](https://github.com/unicode-org/unicodetools/tree/main/unicodetools/src/main/resources/org/unicode/tools/emoji)), so keep that as is.

Mark says that we need not keep the internal input files in paths that have version numbers (or dev for the next version). That means that we can/should move such files out.
- [ ] #310 move .../data/emoji/dev/internal/ files (which are still useful) to .../resource/...
- [ ] #311 move .../data/security/dev/data/ files to .../data/security/internal/

**Comment by macchiati** [comment]
I think the tooling still needs to be straightened out to match the policy
for /dev
