### ISSUE TITLE
invariant: cf restricted to code points defines the same partition as scf

### ISSUE THREAD

**Issue by markusicu** [unicode-org/unicodetools#415]
From https://github.com/unicode-org/properties/issues/23#issuecomment-1437106706 :

add an invariant test that for all code points C, Case_Folding(C) is either equal to Simple_Case_Folding(C) or has two or more code points

**Comment by eggrobin** [comment]
Hm, [whoever suggested this invariant](https://github.com/unicode-org/properties/issues/23#issuecomment-1437106706) was confused.
This is not actually what we want to test, because it is true already:
U+0390 and U+1FD3 both CF to the same thing, but one of the two, and instead to U+03B9 U+0308 U+0301 (likewise for the other characters discussed there).

It sounds like what we want is really
> If two code points have the same case folding, they have the same simple case folding.
