### ISSUE TITLE
Rename the name to "East Asian Spacing"?

### ISSUE THREAD

**Issue by kojiishi** [unicode-org/unicodetools#767]
This issue is a continuation of https://github.com/kojiishi/unicode-auto-spacing/issues/18.
@asmusf @xfq @kidayasuo

**Comment by kojiishi** [comment]
@kidayasuo I'm open to either way. I got some feedback of possible future extensions, so named it as non-East Asian specific, but it's also true that the current spec is very deeply tight into East Asian typography.

I think if it's not too hard to rename specs when we want to extend this to cover other scripts, the "East Asian Spacing" sounds more reasonable. We don't know if this is going to cover other scripts in future.

@kenlunde Thoughts?

**Comment by kenlunde** [comment]
I agree that East Asian Spacing would be a more appropriate name for this property, mainly because that is what started the discussion. It also serves as a practical limit to the scope of the property.

**Comment by macnmm** [comment]
I don't think there is a common-enough "CJK" to do so -- the more we get into "correct" behaviors, the more Japanese seems to need independence from the other more actively evolving scripts, and to my understanding Chinese is more like Japanese (but evolving toward it from a place that was much more simple and wild-west (east?)) and Korean is completely different from the others, also rapidly evolving away from Japanese/Chinese conventions.

**Comment by asmusf** [comment]
I would like to make sure that we focus not on correct _**behavior**_ but on correct _**plain text**_ as the background and preparation for making correct behavior possible by encouraging consistent input --- independent of the actual layout that is then applied to this plain text.

This may require some refocusing of the specification, because it is so tempting to describe **_outcome_** when what we want is an agreement on _**input**_.

With that focus, we should drive towards where the recommended input is language independent, but the fully rendered output may well be different.

Also, since the spec refers to script runs, and we don't have a Japanese vs. Chinese script difference for Han characters, "East Asian" still seems appropriate.

**Comment by kojiishi** [comment]
Thank you for the feedback, @kenlunde, @macnmm, @asmusf.

The renaming to "East Asian" means making it narrower than "Unicode". While I agree with @macnmm that C, J, and K have each different characteristics, the differences aren't a reason not to make it narrower. Maybe what @macnmm is suggesting is to make it even narrower, such as "Han", but this includes Kana, so "Han" looks a bit too narrow.

While @macnmm is right that the proposal doesn't cover everything in East Asian, I think East Asian is a good approximation of what the proposal covers.

**Comment by kojiishi** [comment]
As per the discussions above and no further feedback for 2 weeks, taking the proposal.
